---
- name: Copy frontend manifests to EC2
  copy:
    src: "{{ playbook_dir }}/../techbleat-global-bank-frontend/manifest/"
    dest: /home/ec2-user/k8s/
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Set app image in frontend.yml
  ansible.builtin.replace:
    path: /home/ec2-user/k8s/frontend.yml
    regexp: 'YOUR_ECR_URL/bank-frontend:latest'
    replace: "{{ frontend_service_image }}"

- name: Update kubeconfig for EKS cluster
  become_user: ec2-user
  environment:
    HOME: /home/ec2-user
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  command: >
    aws eks update-kubeconfig
    --name {{ eks_cluster_name }}
    --region {{ aws_region }}

- name: Deploy infrastructure to Kubernetes
  shell: kubectl apply -f /home/ec2-user/k8s/frontend.yml
  become_user: ec2-user
  environment:
    HOME: /home/ec2-user
    KUBECONFIG: /home/ec2-user/.kube/config
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  register: infra_apply

- name: Print infra apply output
  debug:
    msg: "{{ infra_apply.stdout }}"




