apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: __NAMESPACE__
data:
  KAFKA_NODE_ID: "1"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:29092,PLAINTEXT_HOST://kafka-service:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_JMX_PORT: "9101"
  KAFKA_JMX_HOSTNAME: "kafka-service"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:29093"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
  CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  KAFKA_HEAP_OPTS: "-Xms512M -Xmx1G"
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:29092
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/bankingdb
  SPRING_DATASOURCE_USERNAME: bankuser
  SPRING_DATASOURCE_PASSWORD: bankpass
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  DATABASE_URL: postgresql://bankuser:bankpass@postgres-service:5432/bankingdb
  POSTGRES_DB: bankingdb
  POSTGRES_USER: bankuser
  POSTGRES_PASSWORD: bankpass
  FRONTEND_ORIGIN: https://a8da3e529af0643d2ba610ad7044c4f4-1990363720.eu-west-1.elb.amazonaws.com
  KAFKA_BROKER: "kafka-service.banking-dev.svc.cluster.local:9092"
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  SERVER_PORT: "8080"
  ACTIVITY_SERVICE: http://activity-service:8001
  TRANSACTION_SERVICE: http://transaction-service:8080
  USER_SERVICE: http://user-service:8000