apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: __NAMESPACE__
data:
  CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  DATABASE_URL: postgresql://bankuser:bankpass@postgres:5432/bankingdb
  FRONTEND_ORIGIN: https://aaeabe0a13c754cd4988b76b44eb0237-2123364797.eu-west-1.elb.amazonaws.com
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:29092,PLAINTEXT_HOST://kafka-service:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:29092
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-service:29093
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT 
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
  KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  KAFKA_NODE_ID: "1"
  KAFKA_PROCESS_ROLES: broker,controller
  KAFKA_BROKER: "kafka-service.banking-dev.svc.cluster.local:9092"
  KAFKA_JMX_PORT: "9101"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_PASSWORD: bankpass
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankingdb
  SPRING_DATASOURCE_USERNAME: bankuser
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  ACTIVITY_SERVICE: http://activity-service:8001
  TRANSACTION_SERVICE: http://transaction-service:8080
  USER_SERVICE: http://user-service:8000


