apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: __NAMESPACE__
data:
  # ---------- App services ----------
  # User & Activity services
  DATABASE_URL: "postgresql://bankuser:bankpass@postgres:5432/bankingdb"
  FRONTEND_ORIGIN: "https://aaeabe0a13c754cd4988b76b44eb0237-2123364797.eu-west-1.elb.amazonaws.com"

  # Transaction service (Spring Boot)
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/bankingdb"
  SPRING_DATASOURCE_USERNAME: "bankuser"
  SPRING_DATASOURCE_PASSWORD: "bankpass"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SERVER_PORT: "8080"

  # Internal service URLs (if your apps use them)
  ACTIVITY_SERVICE: "http://activity-service:8001"
  TRANSACTION_SERVICE: "http://transaction-service:8080"
  USER_SERVICE: "http://user-service:8000"

