apiVersion: v1
kind: Namespace
metadata:
  name: datadog
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: datadog
type: Opaque
stringData:
  api-key: "${DATADOG_API_KEY}" 
---
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: "tai-key-cluster"
    site: "datadoghq.eu"
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
      clusterChecks:
        enabled: true
      orchestratorExplorer:
        enabled: true
      logCollection:
        enabled: true
        containerCollectAll: true
      apm:
        instrumentation:
          enabled: true
          targets:
            - name: "default-target"
              ddTraceVersions:
                java: "1"
                python: "4"
                js: "5"
                php: "1"
                dotnet: "3"
                ruby: "2"