apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
      - name: bank-app
        image: my-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "96Mi"
            cpu: "100m"
          limits:
            memory: "192Mi"
            cpu: "200m"
