apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: YOUR_ECR_URL/user-service:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "96Mi"
            cpu: "100m"
          limits:
            memory: "192Mi"
            cpu: "200m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: banking-secrets
              key: DATABASE_URL
        - name: FRONTEND_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: banking-config
              key: FRONTEND_ORIGIN

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: user-service
#  namespace: banking
#spec:
#  selector:
#    app: user-service
#  ports:
#    - port: 8000
#      targetPort: 8000
#  type: LoadBalancer
