apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: {{ include "banking-app.namespace" . }}
  labels:
    {{- include "banking-app.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.configmap.kafkaBootstrapServers }}"
  REDIS_HOST: "{{ .Values.configmap.redisHost }}"
  REDIS_PORT: "{{ .Values.configmap.redisPort }}"
  SERVER_PORT: "{{ .Values.configmap.serverPort }}"
  FRONTEND_ORIGIN: "{{ .Values.configmap.frontendOrigin }}"
  KAFKA_NODE_ID: "1"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:29092,PLAINTEXT_HOST://kafka-service:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_JMX_PORT: "9101"
  KAFKA_JMX_HOSTNAME: "kafka-service"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-service:29093"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
  CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "{{ .Values.configmap.springJpaHibernateDdlAuto }}"
  ACTIVITY_SERVICE: "{{ .Values.configmap.activityService }}"
  BANK_FRONTEND: "{{ .Values.configmap.bankFrontend }}"
  TRANSACTION_SERVICE: "{{ .Values.configmap.transactionService }}"
  USER_SERVICE: "{{ .Values.configmap.userService }}"
  ACTIVITY_SERVICE_URL: "http://activity-service..svc.cluster.local:8001"
  USER_SERVICE_URL: "http://user-service..svc.cluster.local:8000"
  TRANSACTION_SERVICE_URL: "http://transaction-service..svc.cluster.local:8080"
  KAFKA_BROKER: "kafka-service..svc.cluster.local:9092"
  POSTGRES_URL: "postgresql://postgres-service..svc.cluster.local:5432/bankingdb"
  REDIS_URL: "redis://redis-service..svc.cluster.local:6379"
  REDIS_CACHE: "{{ .Values.configmap.redisCache }}"
  POSTGRES_DB: "{{ .Values.configmap.postgresDb }}"
  POSTGRES_USER: "{{ .Values.configmap.postgresUser }}"
  POSTGRES_PASSWORD: "{{ .Values.configmap.postgresPassword }}"
  DATABASE_URL: "postgresql://{{ .Values.secrets.postgresUser }}:{{ .Values.secrets.postgresPassword }}@postgres-service:5432/{{ .Values.secrets.postgresDb }}"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/{{ .Values.secrets.postgresDb }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.secrets.postgresUser }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.secrets.postgresPassword }}"
