apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: {{ include "banking-app.namespace" . }}
  labels:
    {{- include "banking-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.secrets.postgresDb }}"
  POSTGRES_USER: "{{ .Values.secrets.postgresUser }}"
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgresPassword }}"
  DATABASE_URL: "postgresql://{{ .Values.secrets.postgresUser }}:{{ .Values.secrets.postgresPassword }}@postgres-service:5432/{{ .Values.secrets.postgresDb }}"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/{{ .Values.secrets.postgresDb }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.secrets.postgresUser }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.secrets.postgresPassword }}"
  NODE_ENV: "{{ .Values.secrets.nodeEnv }}"